apiVersion: v1
kind: Service
metadata:
  name: archivist-es
  namespace: tubearchivist
spec:
  clusterIP: None
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    app: archivist-es
